<?php
/**
 * @file
 * Install hooks for the Open Berkeley Base Feature.
 */

/**
 * Implements hook_install().
 */
function openberkeley_base_install() {
  // Make sure our *_alter() hooks run after the Panopoly versions, in cases
  // where Panopoly already used hook_module_implements_alter() to put itself
  // at the end.
  db_update('system')
    ->fields(array('weight' => 50))
    ->condition('type', 'module')
    ->condition('name', 'openberkeley_base')
    ->execute();
}
